### ISSUE TITLE
Run inference on custom data

### ISSUE THREAD

**Issue by lexical-kenobi** [ivanvovk/controllable-face-generation#1]

**Comment by ivanvovk** [comment]
To run inference on custom data you need to train the proposed solution from scratch:

1. First of all, collect images of needed face. Extract facial keypoints for each.
2. Then you need to finetune ALAE on your images, use code from [here](https://github.com/ivanvovk/controllable-face-generation/blob/master/notebooks/one_guy_finetunning.ipynb). We use VGG19 perceptual loss to minimize identity gap.
3. Use finetuned ALAE and train the model using [this](https://github.com/ivanvovk/controllable-face-generation/blob/master/train_talking_heads.py) script.
